// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIVwQV-MGsk4GKw3UPB-Xdj-_PP_pqRh4',
    appId: '1:1075746629798:web:936822ba674bd41c722c67',
    messagingSenderId: '1075746629798',
    projectId: 'mad-teamsync',
    authDomain: 'mad-teamsync.firebaseapp.com',
    storageBucket: 'mad-teamsync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLeyoFepdp_fhy9jQ45FPPDtmy845ScY',
    appId: '1:1075746629798:android:9b50a50393d1db82722c67',
    messagingSenderId: '1075746629798',
    projectId: 'mad-teamsync',
    storageBucket: 'mad-teamsync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwUQVm5hf2cZWF2OMt-vNTa0KZd-0mgk',
    appId: '1:1075746629798:ios:b9a947d2d03a8837722c67',
    messagingSenderId: '1075746629798',
    projectId: 'mad-teamsync',
    storageBucket: 'mad-teamsync.firebasestorage.app',
    iosBundleId: 'com.example.teamSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwUQVm5hf2cZWF2OMt-vNTa0KZd-0mgk',
    appId: '1:1075746629798:ios:b9a947d2d03a8837722c67',
    messagingSenderId: '1075746629798',
    projectId: 'mad-teamsync',
    storageBucket: 'mad-teamsync.firebasestorage.app',
    iosBundleId: 'com.example.teamSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIVwQV-MGsk4GKw3UPB-Xdj-_PP_pqRh4',
    appId: '1:1075746629798:web:d6ba5ed4e0f40dc4722c67',
    messagingSenderId: '1075746629798',
    projectId: 'mad-teamsync',
    authDomain: 'mad-teamsync.firebaseapp.com',
    storageBucket: 'mad-teamsync.firebasestorage.app',
  );
}
